### ISSUE TITLE
Example Service Call for clean_rooms?

### ISSUE THREAD

**Issue by maniacaris** [simbaja/ha_roomba#2]
Thanks for doing the work on this and making it available. Could you please provide an example of how to properly format a roomba.clean_rooms call with a room specified? I tried referencing the services.yaml and this doesn't error in Home Assistant but the vacuum doesn't do anything:

```
service: roomba.clean_rooms
entity_id: vacuum.roomba
data:
  pmap: "################"
  regions: "[{region_id: 1, type: rId}]"
```
